import os
import re
from fpdf import FPDF

FONT_DIR = os.path.join(os.path.dirname(__file__), "fonts")

LANGUAGE_FONT_MAP = {
    "English": "NotoSans-Regular.ttf",
    "French": "NotoSans-Regular.ttf",
    "German": "NotoSans-Regular.ttf",
    "Spanish": "NotoSans-Regular.ttf",
    "Hindi": "NotoSansDevanagari-Regular.ttf",
    "Marathi": "NotoSansDevanagari-Regular.ttf",
    "Tamil": "NotoSansTamil-Regular.ttf",
    "Malayalam": "NotoSansMalayalam-Regular.ttf",
    "Gujarati": "NotoSansGujarati-Regular.ttf",
    "Telugu": "NotoSansTelugu-Regular.ttf",
    "Bengali": "NotoSansBengali-Regular.ttf",
    "Urdu": "NotoSansArabic-Regular.ttf",
}

DEFAULT_FONT = "NotoSans-Regular.ttf"

# Non-Latin scripts need a bit more line height (conjuncts / matras) and
# read a little better slightly larger than 10pt Latin body text.
LINE_HEIGHT_MAP = {
    "Hindi": 7.5,
    "Marathi": 7.5,
    "Tamil": 7.5,
    "Malayalam": 8.0,
    "Gujarati": 7.5,
    "Telugu": 7.5,
    "Bengali": 7.5,
    "Urdu": 7.5,
}
DEFAULT_LINE_HEIGHT = 6.0

FONT_SIZE_MAP = {lang: 11 for lang in LINE_HEIGHT_MAP}
DEFAULT_FONT_SIZE = 10

# A single professional accent color used for the title, section bands
# and separators, so the document reads as one designed piece.
ACCENT_COLOR = (31, 73, 125)      # deep blue
ACCENT_TEXT_COLOR = (255, 255, 255)
META_TEXT_COLOR = (100, 100, 100)
BODY_TEXT_COLOR = (30, 30, 30)

SECTION_HEADINGS = (
    "MEETING SUMMARY:",
    "KEY DISCUSSIONS:",
    "DECISIONS TAKEN:",
    "ACTION ITEMS:",
)

META_PREFIXES = ("Date", "Participants", "Language")


def _extract_title(text: str) -> str:
    """Pull the value after 'Title :' / 'Title:' from the generated text."""
    match = re.search(r"^\s*Title\s*:\s*(.+)$", text, flags=re.MULTILINE)
    if match:
        return match.group(1).strip()
    return ""


def _slugify(value: str, fallback: str = "Minutes_of_Meeting", maxlen: int = 80) -> str:
    """Turn a meeting title into a safe filename stem."""
    if not value:
        return fallback
    cleaned = re.sub(r'[<>:"/\\|?*\n\r\t]', "", value).strip()
    cleaned = re.sub(r"\s+", "_", cleaned)
    cleaned = cleaned.strip("_")
    return cleaned[:maxlen] if cleaned else fallback


def _resolve_path(text: str, filepath: str, output_dir: str, ext: str) -> str:
    """If no explicit filepath was given, build one from the meeting title."""
    if filepath:
        os.makedirs(os.path.dirname(filepath) or ".", exist_ok=True)
        return filepath
    os.makedirs(output_dir, exist_ok=True)
    title = _extract_title(text)
    filename = f"{_slugify(title)}.{ext}"
    return os.path.join(output_dir, filename)


def export_txt(text: str, filepath: str = None, output_dir: str = "outputs") -> str:
    filepath = _resolve_path(text, filepath, output_dir, "txt")
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(text)
    return filepath


class MoMPDF(FPDF):
    """FPDF subclass so we can draw a page-number footer automatically."""
    footer_font = "Helvetica"

    def footer(self):
        self.set_y(-15)
        self.set_font(self.footer_font, "", 8)
        self.set_text_color(*META_TEXT_COLOR)
        self.cell(0, 10, f"Page {self.page_no()}", align="C")


def export_pdf(text: str,
                filepath: str = None,
                language: str = "English",
                output_dir: str = "outputs") -> str:

    # Remove excessive blank lines generated by the LLM
    text = re.sub(r"\n{3,}", "\n\n", text)

    meeting_title = _extract_title(text) or "Minutes of Meeting"
    filepath = _resolve_path(text, filepath, output_dir, "pdf")

    font_file = LANGUAGE_FONT_MAP.get(language, DEFAULT_FONT)
    font_path = os.path.join(FONT_DIR, font_file)
    default_path = os.path.join(FONT_DIR, DEFAULT_FONT)

    line_height = LINE_HEIGHT_MAP.get(language, DEFAULT_LINE_HEIGHT)
    body_size = FONT_SIZE_MAP.get(language, DEFAULT_FONT_SIZE)

    pdf = MoMPDF()
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.set_margins(18, 18, 18)

    if os.path.exists(font_path):
        pdf.add_font("Body", "", font_path)
        bold_path = font_path.replace("Regular", "Bold")
        if os.path.exists(bold_path):
            pdf.add_font("Body", "B", bold_path)
            bold_ok = True
        else:
            bold_ok = False
        body = "Body"
        if font_file != DEFAULT_FONT and os.path.exists(default_path):
            pdf.add_font("Latin", "", default_path)
            pdf.set_fallback_fonts(["Latin"])
    else:
        print(f"WARNING : Font not found -> {font_path}")
        body = "Helvetica"
        bold_ok = True

    pdf.footer_font = body
    pdf.add_page()

    page_width = pdf.epw

    def font(size=body_size, bold=False):
        if body == "Body" and bold and not bold_ok:
            pdf.set_font(body, "", size)
        else:
            pdf.set_font(body, "B" if bold else "", size)

    def separator(color=(210, 210, 210)):
        y = pdf.get_y()
        pdf.set_draw_color(*color)
        pdf.line(pdf.l_margin, y, pdf.w - pdf.r_margin, y)
        pdf.ln(4)

    def title_block(meeting_title):
        pdf.set_text_color(*ACCENT_COLOR)
        font(19, True)
        pdf.multi_cell(0, 10, meeting_title, align="C")
        pdf.set_text_color(*BODY_TEXT_COLOR)
        pdf.ln(1)
        separator(ACCENT_COLOR)

    def meta_line(text):
        font(9)
        pdf.set_text_color(*META_TEXT_COLOR)
        pdf.cell(0, 6, text, align="C", new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(*BODY_TEXT_COLOR)

    def heading(text):
        pdf.ln(3)
        font(12, True)
        pdf.set_fill_color(*ACCENT_COLOR)
        pdf.set_text_color(*ACCENT_TEXT_COLOR)
        pdf.cell(0, 9, "  " + text.replace(":", ""), fill=True,
                 new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(*BODY_TEXT_COLOR)
        pdf.ln(3)

    def normal(text):
        font(body_size)
        pdf.multi_cell(page_width, line_height, text)

    def bullet(text):
        font(body_size)
        pdf.set_x(pdf.l_margin + 5)
        pdf.multi_cell(page_width - 5, line_height, "-  " + text)

    def check_page():
        if pdf.get_y() > (pdf.h - 30):
            pdf.add_page()

    title_printed = False

    for raw_line in text.splitlines():
        line = re.sub(r"[ \t]+", " ", raw_line).strip()
        if not line:
            continue

        check_page()

        # Ignore separator lines from the generated text
        if line.startswith("="):
            continue

        # Main title: draw once, using the meeting title, not "MINUTES OF MEETING"
        elif line == "MINUTES OF MEETING":
            if not title_printed:
                title_block(meeting_title)
                title_printed = True

        # The raw "Title : ..." line is now shown as the heading above, skip it
        elif line.startswith("Title"):
            continue

        # Remaining header info (Date / Participants / Language)
        elif any(line.startswith(p) for p in META_PREFIXES):
            meta_line(line)

        # Section headings
        elif line in SECTION_HEADINGS:
            heading(line)

        # Bullet points (Action Items, etc. — kept as points, not a table)
        elif line.startswith("-"):
            bullet(line[1:].strip())

        # End of Minutes
        elif line == "End of Minutes":
            pdf.ln(5)
            separator()
            font(10, True)
            pdf.cell(0, 8, "End of Minutes", align="C",
                     new_x="LMARGIN", new_y="NEXT")

        # Normal paragraph
        else:
            normal(line)

    pdf.output(filepath)
    return filepath